apiVersion: v1
kind: Service
metadata:
  name: sentiment-app-service
  namespace: sentiment-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "80"
spec:
  type: LoadBalancer
  selector:
    app: sentiment-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
